### ISSUE TITLE
Suggest use `~` instead of `-`

### ISSUE THREAD

**Issue by huyz** [thingnotok/obsidian-toggle-list#3]
`~` already means strikeout in Markdown. Better to reuse that association in `[~]`.  And then I suggest to use `wavy line-through` instead of straight `line-through` which is already associated with the usual "done" state in many themes, including the default Obsidian theme.

It's also less likely to clash with other people's pre-existing use of `[-]`

**Comment by thingnotok** [comment]
Hi, you can configure whatever states you want in setting>ToggleList>state. And how the checkbox states are rendered depends on the Theme you choose. But as you mentioned, the suggestion in README is confuing , I'll update the figures in next release.

- [ ] fix the readme description on [-] -> [~], and update the figures.

**Comment by thingnotok** [comment]
Hi, on a second thought, since the default theme is now Minimal theme, and what it support is - [-], I'm gonna stick with the current example. 

However, you can still set `- [~]`  in your state group and add a css with wacv line-through for you need. Here's an example css for -[~] on Default Theme. You can create a `wavy.css` file under `Vault/.obsidian/snippets` and enable it in Appearance/ CSS Snippets.  Hope this can help 👍 

```css
li[data-task="~"]>p>input:checked,
li[data-task="~"]>input:checked,
input[data-task="~"]:checked,
li[data-task="~"]>p>input:checked {
  --checkbox-marker-color: transparent;
  background-color: currentColor;
  color: var(--text-faint);
  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' class='h-5 w-5' viewBox='0 0 20 20' fill='currentColor'%3E%3Cpath fill-rule='evenodd' d='M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z' clip-rule='evenodd' /%3E%3C/svg%3E");
}
body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="~"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="~"].task-list-item.is-checked,
body:not(.tasks) li[data-task="~"].task-list-item.is-checked {
  color: var(--text-faint);
  text-decoration: wavy line-through var(--text-faint) 1px;
}
```
